spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bt22?jdbcCompliantTruncation=false&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&useFastDateParsing=false&sessionVariables=sql_mode=""
    username: root
    password:

configs:
  security:
    authentication:
      jwt:
        app-authorization: ${APP_AUTHORIZATION:BT22}
        header: ${JWT_HEADER:Authorization}
        expires-in : ${JWT_EXPIRES_IN:600}
        cookie: ${JWT_COOKIE:AUTH-TOKEN}
        hikari:
          minimum-idle: ${HIKARI_MIN_IDLE:2}
          maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:8}

logging:
  level:
    root: INFO

  flyway:
  enabled: true
  baseline-one-migrate: true
  validateMigrationNaming: false